"""Generate the brief submission report from measured experiment artifacts."""
import json
from pathlib import Path
from xml.sax.saxutils import escape
from reportlab.platypus import SimpleDocTemplate,Paragraph,Table,TableStyle,Spacer,PageBreak
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib import colors
ROOT=Path(__file__).resolve().parents[1]
m=json.loads((ROOT/'reports/metrics.json').read_text());c=json.loads((ROOT/'reports/challenge_results.json').read_text())
sections=[
('Objective and implementation','ShopAssist is an online-ready voice-enabled shopping-support chatbot. It accepts English speech or typed text, displays the recognized transcript, predicts one of 27 support intents using a trained BiLSTM, and generates controlled responses from fictional order records. The core flows are order tracking, cancellation, returns and refund tracking. Additional flows show invoices and change the address of an unshipped order. The application uses Python/Flask, PyTorch, SQLite, HTML, CSS and JavaScript.'),
('Dataset and provenance','The source is Bitext Innovations’ Customer Support 27K v11 dataset: 26,872 instructions labelled with 27 intents. It uses a synthetic/hybrid generation process, not transcripts collected from this application. The included projection retains row number, flags, text, category and intent; generic response text is excluded. Bitext-derived data is distributed with its CDLA-Sharing 1.0 license and attribution. Source Git blob: 404649b80bb5ec57463d7ce7e17bc48e63b01fbc.'),
('Splitting and conversational supplement',f'After lowercasing, placeholder normalization and deduplication, 23,619 unique examples remain; 3,253 duplicate rows were removed and no conflicting normalized labels were found. A stratified seed-42 split yields 16,533 original training examples, 3,543 validation examples and 3,543 test examples. A first model scored 99.07% on the synthetic test set but failed short sanity-check questions. To address that observed weakness, {m["authored_supplement_samples"]:,} author-written/templated conversational training examples were added, giving {m["train_samples"]:,} training records. Supplement matches to validation/test text were excluded. The same synthetic test split was revisited after development; it is not an independent final evaluation. Closely related synthetic templates can still occur across splits.'),
('Speech recognition and application pipeline','Microphone audio is transcribed through the browser SpeechRecognition/webkitSpeechRecognition API with en-IN language, interim results and one utterance per recording. The transcript stays editable until the user sends it. The browser provider supplies the acoustic recognizer; no speech model is trained in this project. Recognition may use remote processing. The app handles unsupported browsers, denied permission, silence and network errors, with typed chat as fallback. Optional browser speech synthesis reads replies aloud. Pipeline: audio -> transcript -> token IDs -> BiLSTM -> intent -> dialogue state and SQLite lookup -> displayed/spoken response.'),
('Deep-learning architecture',f'Text is Unicode-normalized and lowercased; numbers and dataset placeholders become the token entity. Word tokens are mapped to a training-only vocabulary of {m["vocabulary_size"]:,} entries, with padding and unknown tokens, and truncated to 40 words. The model uses Embedding(64), a single bidirectional LSTM with 64 hidden units in each direction, concatenated final hidden states (128 dimensions), dropout 0.3, Dense(64) with ReLU, dropout 0.2 and Dense(27). Softmax gives intent scores. There are {m["parameters"]:,} trainable parameters. The BiLSTM learns sequence features; the separate dialogue manager does not replace the learned classifier with keyword routing.'),
('Training and prediction policy',f'Training uses multiclass cross-entropy, AdamW (learning rate 0.002, weight decay 0.0001), batch size 128, gradient clipping at 1.0 and seed 42. Training ran {m["epochs_run"]} epochs, with the best validation macro-F1 checkpoint from epoch {m["selected_epoch"]}. PyTorch {m["torch_version"]} ran on CPU with two threads; the measured training duration was {m["training_seconds"]:.2f} seconds in the build environment. Validation selects the lowest tested score threshold with at least 98% accuracy among accepted validation predictions, subject to a fixed 0.15 margin. The selected threshold is {m["threshold"]:.2f}; deployment also requires at least 50% vocabulary coverage. These are heuristic rejection rules, not calibrated confidence or a dependable out-of-domain detector.'),
('Conversation state and database behavior','A signed, opaque browser session identifies isolated SQLite state containing five fictional orders. Missing order IDs, return reasons and new addresses are collected in follow-up turns. Exact confirmations and control replies are handled deterministically. The classifier handles new support requests. Cancellation requires processing status; return requests require delivery within 14 days. Each change is proposed before confirmation. Shipped orders cannot be cancelled. Refund status is read from records, not invented by a language model. Request IDs make retries idempotent. Reset affects only the current session. No real purchases, payments, emails, human-agent transfers or return pickups occur.'),
('Testing and limitations',f'All 17 automated functional tests passed with the actual trained classifier. They cover tracking, positive/negative confirmations, cancellation eligibility, returns, expired return windows, address changes, invoices, unknown orders, intent switching, session isolation, retries and invalid input. JavaScript syntax checks passed. A separate author-written challenge of 40 new questions across 10 intents scored {100*c["accuracy"]:.1f}% accuracy. This challenge was not used for model fitting or threshold selection, but it is still small and not independently sourced. The model accepted {round(c["coverage"]*c["count"])} of 40 questions; only {c["accepted_correct"]} accepted predictions were correct. It rejected {c["ood_rejected"]} of {c["ood_count"]} unrelated probes. Thus the synthetic held-out score substantially overestimates performance on unfamiliar phrasing. Short paraphrases, missing vocabulary, mixed intents and implicit references remain weaknesses.'),
('Deployment and remaining validation','Dockerfile, Gunicorn entry point and render.yaml are included for an external public Render web service. The frontend and API share one origin. The service binds to the supplied PORT, exposes /health and runs one worker with four threads. The model checkpoint ships with the app, so deployment does not train or download a model. SECRET_KEY should be a host-managed secret and COOKIE_SECURE=1 on HTTPS. Free-host restarts can reset the disposable SQLite database and cold starts may delay the first request. No successful external deployment or live URL is claimed at report creation; deployment remains pending. Browser UI and microphone accuracy are also unverified because the separate browser-preview environment could not run the Python application.'),
('Speech evaluation and future work','Before submission, test the public HTTPS link on a real device. Record at least 20 unedited spoken test transcripts and calculate word error rate: (substitutions + deletions + insertions) / reference words. Also measure intent accuracy from those transcripts and end-to-end latency. None of these speech measurements has been completed; CPU classifier latency is not a substitute. Future improvements include independently collected support questions, stronger semantic representations, explicit out-of-domain examples, calibrated rejection and a broader untouched external test set. A production deployment would additionally need real authentication, authorization and durable storage.')]
rows=[['Metric','Measured result'],['Synthetic held-out text accuracy',f'{100*m["test_accuracy"]:.2f}% (n={m["test_samples"]:,})'],['Synthetic held-out macro-F1',f'{m["macro_f1"]:.4f}'],['Accepted synthetic test coverage',f'{100*m["accepted_coverage"]:.2f}%'],['Accepted synthetic test accuracy',f'{100*m["accepted_accuracy"]:.2f}%'],['New authored challenge accuracy',f'{100*c["accuracy"]:.1f}% (n={c["count"]})'],['Unrelated inputs rejected',f'{c["ood_rejected"]}/{c["ood_count"]}'],['Median CPU inference on challenge',f'{c["median_inference_ms"]:.2f} ms (environment-specific)'],['Functional API/state tests','17/17 passed'],['Speech WER / live browser / external deployment','Not yet verified']]
refs=['Bitext dataset: https://huggingface.co/datasets/bitext/Bitext-customer-support-llm-chatbot-training-dataset','Bitext source: https://github.com/bitext/customer-support-llm-chatbot-training-dataset','SpeechRecognition: https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition','Render Docker: https://render.com/docs/docker','Render free-instance behavior: https://render.com/docs/free']
markdown='# ShopAssist: Voice-Enabled Shopping Support\n\nBrief project report | 27 September 2026\n\n'
for i,(h,t) in enumerate(sections):
 markdown+=f'## {i+1}. {h}\n\n{t}\n\n'
 if h=='Conversation state and database behavior':markdown+='## Measured results\n\n'+'\n'.join('| '+' | '.join(r)+' |' for r in [rows[0],['---','---']]+rows[1:])+'\n\n'
markdown+='## References\n\n'+'\n\n'.join(refs)+'\n'
(ROOT/'reports/REPORT.md').write_text(markdown)
styles=getSampleStyleSheet();styles.add(ParagraphStyle(name='TitleX',fontName='Helvetica-Bold',fontSize=24,leading=29,textColor=colors.HexColor('#123d3b'),spaceAfter=10));styles.add(ParagraphStyle(name='HeadX',fontName='Helvetica-Bold',fontSize=12,leading=16,textColor=colors.HexColor('#123d3b'),spaceBefore=12,spaceAfter=6,keepWithNext=True));styles.add(ParagraphStyle(name='BodyX',fontName='Helvetica',fontSize=9.5,leading=13.5,textColor=colors.HexColor('#304940'),spaceAfter=7));styles.add(ParagraphStyle(name='CellX',fontName='Helvetica',fontSize=9,leading=12))
# ASCII punctuation avoids missing glyphs in standard PDF fonts.
def clean(s):return s.replace('’',"'").replace('–','-').replace('—','-').replace('“','"').replace('”','"')
def p(s,style='BodyX'):return Paragraph(escape(clean(s)),styles[style])
story=[p('ShopAssist','TitleX'),p('Voice-Enabled Shopping Support | Brief Project Report'),p('27 September 2026 | External deployment pending')]
for i,(h,t) in enumerate(sections):
 story.extend([p(f'{i+1}. {h}','HeadX'),p(t)])
 if h=='Conversation state and database behavior':
  story.append(p('Measured results','HeadX'))
  table=Table([[p(cell,'CellX') for cell in row] for row in rows],colWidths=[258,233],repeatRows=1)
  table.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#dbeae3')),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.HexColor('#f3f7f4'),colors.white]),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),8),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));story.append(table)
story.append(p('References','HeadX'));story.extend(p(r) for r in refs)
def footer(canvas,doc):
 canvas.setStrokeColor(colors.HexColor('#c6d8ce'));canvas.line(52,42,543,42);canvas.setFont('Helvetica',8);canvas.setFillColor(colors.HexColor('#657e70'));canvas.drawString(52,28,'ShopAssist | Dataset, model, methodology and results');canvas.drawRightString(543,28,str(doc.page))
SimpleDocTemplate(str(ROOT/'reports/ShopAssist_Report.pdf'),pagesize=(595.28,841.89),leftMargin=52,rightMargin=52,topMargin=42,bottomMargin=57,title='ShopAssist Project Report').build(story,onFirstPage=footer,onLaterPages=footer)
print('Report generated')
